name: "Deploy Documentation"
on: 
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    
#     - name: Make Sphinx
#       uses: ammaraskar/sphinx-action@master
#       with:
#           docs-folder: "source"
#           build-command: "sphinx-build . build"
          
    - name: Make Sphinx python
      uses: actions/setup-python@master
      with:
          python-version: 3.8
    - name: build
      run: |
         /opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip
         pip3 install -r source/requirements.txt
         pip3 install setuptools
         sudo python3 setup.py install
         make html
      
    
    # Push the HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./source/build   
